### ISSUE TITLE
a

### ISSUE THREAD

**Issue by d-o-g** [kinztechcom/OSRS-Refactored#3]
https://github.com/kinztechcom/OSRS-Refactored/blob/master/src/OnlineFriend.java#L3 lol y r u putting author tags on rs code topkek

**Comment by allenkinzalow** [comment]
Intellij does that automatically...?

**Comment by gucciflipflops11** [comment]
lol wat, did u manually create the class

**Comment by allenkinzalow** [comment]
No but I created the comment at the top of the class which automatically includes an author tag. Either way, it signifies who was responsible or contributed to the class.
